# Generated by Django 4.0.5 on 2022-07-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='create_data',
            new_name='created_data',
        ),
    ]
