# Generated by Django 4.0.5 on 2022-07-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_rename_create_data_team_created_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
